config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'games#index'
  resources :games do
    post 'forfeit', on: :member
    resources :pieces, only: [:index, :update]

  end


end

app/models/game.rb
# rubocop:disable Metrics/AbcSize
# rubocop:disable Metrics/MethodLength

class Game < ApplicationRecord
  has_many :participations
  has_many :pieces
  has_many :moves

  scope :available,
        lambda {
          where('(white_player_id IS NULL AND black_player_id IS NOT NULL)
          OR
          (white_player_id IS NOT NULL AND black_player_id IS NULL)')
        }

  def populate_board
    # White pieces
    Rook.create(game_id: id, user_id: white_player_id, row: 0, col: 0, is_black: false)
    Knight.create(game_id: id, user_id: white_player_id, row: 0, col: 1, is_black: false)
    Bishop.create(game_id: id, user_id: white_player_id, row: 0, col: 2, is_black: false)
    Queen.create(game_id: id, user_id: white_player_id, row: 0, col: 3, is_black: false)
    King.create(game_id: id, user_id: white_player_id, row: 0, col: 4, is_black: false)
    Bishop.create(game_id: id, user_id: white_player_id, row: 0, col: 5, is_black: false)
    Knight.create(game_id: id, user_id: white_player_id, row: 0, col: 6, is_black: false)
    Rook.create(game_id: id, user_id: white_player_id, row: 0, col: 7, is_black: false)
    (0..7).each do |i|
      Pawn.create(game_id: id,
                  user_id: white_player_id,
                  row: 1,
                  col: i,
                  is_black: false)
    end

    # Black pieces
    (0..7).each do |i|
      Pawn.create(game_id: id,
                  user_id: black_player_id,
                  row: 6,
                  col: i,
                  is_black: true)
    end
    Rook.create(game_id: id, user_id: black_player_id, row: 7, col: 0, is_black: true)
    Knight.create(game_id: id, user_id: black_player_id, row: 7, col: 1, is_black: true)
    Bishop.create(game_id: id, user_id: black_player_id, row: 7, col: 2, is_black: true)
    Queen.create(game_id: id, user_id: black_player_id, row: 7, col: 3, is_black: true)
    King.create(game_id: id, user_id: black_player_id, row: 7, col: 4, is_black: true)
    Bishop.create(game_id: id, user_id: black_player_id, row: 7, col: 5, is_black: true)
    Knight.create(game_id: id, user_id: black_player_id, row: 7, col: 6, is_black: true)
    Rook.create(game_id: id, user_id: black_player_id, row: 7, col: 7, is_black: true)
  end

  def blacks_turn?
    !moves.empty && !moves.last.piece.is_black
  end

  def set_turn
    move_number = moves.count
    move_number.even? ? white_player_id : black_player_id
  end

  class Board
    attr_reader :grid

    def initialize(pieces)
      @pieces = pieces.are_not_captured
      @grid = Array.new(8) { Array.new(8) }
      fill_grid
    end

    private

    attr_reader :pieces

    def fill_grid
      pieces.each do |piece|
        if grid[piece.row][piece.col]
          raise "uncaptured pieces occupy same square"
        end
        grid[piece.row][piece.col] = piece
      end
    end
  end

  def piece_at(row, col)
    pieces.where(row: row, col: col).first
  end

  def forfeit(current_user)
    winner_id = current_user.id == white_player_id ? black_player_id : white_player_id
    update_attributes(winner_id: winner_id, result: 'Forfeit')
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :update]

  def index
    @games = Game.available
  end

  def create
    game = Game.create(white_player_id: current_user.id)
    current_user.games << game
    redirect_to game
  end

  def new
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
  end

  # Join a Game
  # Current_user_id becomes black_player_id
  # For given game assign (update) current_user_id to black_player_id

  def update
    @game = Game.find(params[:id])
    black_player? unless @game.black_player_id.present?
    if @game.valid?
      update_valid_game
    else
      render :index, text: "Not Allowed. Invalid Game"
    end
  end

  def forfeit
    @game = Game.find(params[:id])
    @game.forfeit(current_user)
    flash[:alert] = 'You have forfeited the game.'
    redirect_to games_path
  end

  private

  def black_player?
    return false if @game.white_player_id == current_user.id
    @game.update_attributes(black_player_id: current_user.id)
  end

  def update_valid_game
    current_user.games << @game
    @game.populate_board if @game.pieces.empty?
    redirect_to @game
  end

  def game_params
    params.require(:game).permit(:black_player_id)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<%= link_to "Sample Game (development)", game_path(Game.first) %>

<% current_user = User.first %>

<%= button_to "Start a New Game", games_path, class: "btn btn-success" %>

<h1>Join A Game</h1>

<% @games.each do |game| %>
  <% user= User.find(game.white_player_id) %>
  <%= user.screen_name %>
  <%= form_for game do |f| %>
    <%= f.hidden_field :black_player_id, value: current_user.id %>
    <%= f.submit "Join Game" %>
  <% end %>

<% end %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= button_to "Create Demo Game", games_path %>

<% link_to games_path %>

app/views/games/show.html.erb
<br />

<div class="container">
  <%= button_to "Forfeit Game", forfeit_game_path(@game.id), class: "btn btn-danger" %>

  <div class="chessboard" data-pieces-url="<%= game_pieces_path(@game) %>">
    <% (0..7).each do |row| %>
      <% (0..7).each do |col| %>
        <div class="square <%= (row + col) % 2 == 0 ? "light" : "dark" %>"
          id="<%= row.to_s + col.to_s %>"></div>
      <% end %>
    <% end %>
  </div>
</div>

<script src="https://www.gstatic.com/firebasejs/3.7.6/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/3.7.6/firebase-database.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: '<%= ENV["apiKey"] %>',
    authDomain: '<%= ENV["authDomain"] %>',
    databaseURL: '<%= ENV["databaseURL"] %>',
    storageBucket: '<%= ENV["storageBucket"] %>'
  };
  firebase.initializeApp(config);

  var piecesURL = $('.chessboard').data('pieces-url'); console.log(piecesURL);
  var gameId = piecesURL.split('/')[2];
  var firebaseGame = firebase.database().ref(gameId);
  console.log(firebaseGame);

  var whitePieceHtml = {
    King: '&#9812;',
    Queen: '&#9813;',
    Rook: '&#9814;',
    Bishop: '&#9815;',
    Knight: '&#9816;',
    Pawn: '&#9817;'
  };
  var blackPieceHtml = {
    King: '&#9818;',
    Queen: '&#9819;',
    Rook: '&#9820;',
    Bishop: '&#9821;',
    Knight: '&#9822;',
    Pawn: '&#9823;'
  };

  $(function() {
    requestPieces();

    firebaseGame.on('value', function(snapshot) {
      var turn = snapshot.val().turn;
      var turnHtml = '<h2 class="turn">' + turn + '</h2>'
      $('.turn').remove();
      $('.booyah-box').append(turnHtml);
      requestPieces();
    });

    function requestPieces() {
      $.get(piecesURL).success(function(pieces) {
        updateBoard(pieces);
      });
    }

    function updateBoard(pieces) {
      $('.piece').remove();
      pieces.forEach(function(piece, i) {
        if (piece.row > -1 && piece.col > -1) {
          placePiece(piece);
        }
      });

      function placePiece(piece) {
        var squareId = String(piece.row) + String(piece.col);
        var pieceHtml = "";
        if (piece.is_black) {
          pieceHtml = blackPieceHtml[piece.type];
        } else {
          pieceHtml = whitePieceHtml[piece.type];
        }
        var piece = $.parseHTML(
          '<div class="piece" data-id='+ piece.id +'>' + pieceHtml + '</div>');
        $('.square#'+squareId).append(piece);
        $('.piece').draggable();
      }
    }

    $(".square").droppable({
      drop: function(event, ui) {
        var coord = $(this).attr('id').split('');
        var $piece = $(ui.draggable);
        movePiece($piece, coord);
      }
    });

    function movePiece(piece, coord) {
      var newRow = coord[0];
      var newCol = coord[1];

      $.post(piecesURL + "/" + piece.data("id"), {
        _method: "PUT",
        piece: { row: newRow, col: newCol }
      }).success(function(pieces) {
        updateBoard(pieces);
      });
    }
  });
</script>